version: '3.9'
services:
  backend:
    build:
      context: ./Goin
      dockerfile: Dockerfile
    container_name: backend
    environment:
      API_KEY: "${API_KEY}"
      DJANGO_SUPERUSER_USERNAME: ${ADMIN_NAME}
      DJANGO_SUPERUSER_EMAIL: ${ADMIN_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${ADMIN_PASSWORD}
    command: >
      sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py createsuperuser --noinput &&
      python manage.py runserver 0.0.0.0:80"
    ports:
      - "80:80"
