version: '3.9'
services:
  backend:
    build:
      context: ./Goin
      dockerfile: Dockerfile
    container_name: backend
    environment:
      API_KEY: "${API_KEY}"
      DJANGO_SUPERUSER_USERNAME: "admin3"
      DJANGO_SUPERUSER_EMAIL: "admin@gmail.com"
      DJANGO_SUPERUSER_PASSWORD: "Def2638234"
    command: >
      sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py createsuperuser --noinput &&
      python manage.py runserver 0.0.0.0:80"
    ports:
      - "80:80"
