version: '3.9'
services:
  backend:
    build:
      context: ./Goin/
      dockerfile: Dockerfile
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver  & python manage.py bot"
    container_name: Drf
    env_file:
      - .env
    ports:
      - "8000:8000"
