# Generated by Django 4.2.5 on 2023-10-01 07:40

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Название продукта')),
                ('descriptions', models.TextField(verbose_name='Описание продукта')),
                ('price', models.IntegerField(default=0, verbose_name='Цена продукта')),
                ('created_at', models.DateField(auto_now=True, verbose_name='Дата создание продукта')),
                ('modified_at', models.DateField(auto_now_add=True, verbose_name='Дата изменение продукта')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Категория продукта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Фотография продукта')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name': 'Изображения продукта',
                'verbose_name_plural': 'Изображении продукта',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=155, verbose_name='Имя клиента')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта клиента')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес клиента')),
                ('payment_method', models.CharField(choices=[('Оплата наличными', 'Оплата наличными'), ('Оплата переводом', 'Оплата переводом')], max_length=50, verbose_name='Способ оплаты')),
                ('delivery_method', models.CharField(choices=[('Самовывоз', 'Самовывоз'), ('Доставка к дому', 'Доставка к дому')], max_length=50, verbose_name='Способ доставки')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона клиента')),
                ('comment', models.TextField(verbose_name='Комментария к заказу')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Заказать продукт',
                'verbose_name_plural': 'Заказанные продкуты',
            },
        ),
    ]
