# Generated by Django 4.2.5 on 2023-10-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_created_at_remove_product_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='', verbose_name='Изображение продукта'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductImages',
        ),
    ]
