# Generated by Django 4.2.5 on 2023-10-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image_delete_productimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=1, verbose_name='Имеется в наличие'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Старая цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='popular',
            field=models.BooleanField(blank=True, null=True, verbose_name='Популярная'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=1, verbose_name='Вес продукта'),
            preserve_default=False,
        ),
    ]
