# Generated by Django 4.2.5 on 2023-11-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to='', verbose_name='Изображение категории'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='popular',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Популярная'),
        ),
    ]
